### ISSUE TITLE
“sodium.h”: No such file or directory

### ISSUE THREAD

**Issue by bigtan** [shadowsocks/libsscrypto#1]
Following the `Build` section in the project, the vs2015 report such error:

```
错误  C1083   无法打开包括文件: “sodium.h”: No such file or directory
```

**Comment by GangZhuo** [comment]
See https://github.com/GangZhuo/libsscrypto/blob/master/README.md

```
git submodule init
git submodule update
```

**Comment by GangZhuo** [comment]
重新 git clone 一次，之前的配置的头文件查找目录是我电脑上的绝对路径。
