### ISSUE TITLE
mbedtls为空？

### ISSUE THREAD

**Issue by dai-2584** [shadowsocks/libsscrypto#9]
下载下来mbedtls文件夹为空、 libsodium文件夹为空，只有hkdf.c和cipher_get_size_ex.c两个C文件，VC2017编译通不过，怎么回事？

**Comment by Noisyfox** [comment]
`git submodule update`

**Comment by A-Kuang-25** [comment]
I choose  Download ZIP, I unzip it and open it with VS2017, but I can't compile it

**Comment by A-Kuang-25** [comment]
There are only two C files under the libsscrypto folder.

**Comment by Noisyfox** [comment]
https://github.com/shadowsocks/libsscrypto#build

Follow the instructions.

**Comment by A-Kuang-25** [comment]
Hello, according to your prompt method or not, can you send a copy of your local source code to me? Mailbox (jiasuqi2016@gmail.com),Thank you!

**Comment by celeron533** [comment]
> can you send a copy of your local source code to me

Source code is already HERE.
